# Generated by Django 4.0.2 on 2022-03-12 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseapp', '0001_initial'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationstudentrel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.student'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.course'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='students',
            field=models.ManyToManyField(through='courseapp.PresentationStudentRel', to='userapp.Student'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.presentation'),
        ),
        migrations.AddField(
            model_name='homeworkstudentrel',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.homework'),
        ),
        migrations.AddField(
            model_name='homeworkstudentrel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.student'),
        ),
        migrations.AddField(
            model_name='homework',
            name='answers',
            field=models.ManyToManyField(through='courseapp.HomeworkStudentRel', to='userapp.Student'),
        ),
        migrations.AddField(
            model_name='homework',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.presentation'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.teacher'),
        ),
        migrations.AddConstraint(
            model_name='presentationstudentrel',
            constraint=models.UniqueConstraint(fields=('student', 'presentation'), name='unique attendancy'),
        ),
        migrations.AddConstraint(
            model_name='homeworkstudentrel',
            constraint=models.UniqueConstraint(fields=('student', 'homework'), name='unique answer'),
        ),
    ]
