# Generated by Django 4.0.2 on 2022-02-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersentationStudentRel',
            new_name='PrsentationStudentRel',
        ),
    ]
