# Generated by Django 4.0.2 on 2022-02-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_remove_persentationstudentrel_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persentationstudentrel',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='course grade'),
        ),
    ]
