# Generated by Django 4.0.2 on 2022-02-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('courseapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presentationstudentrel',
            unique_together={('student', 'presentation')},
        ),
    ]
