# Generated by Django 3.2.7 on 2022-02-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='username')),
                ('name', models.CharField(max_length=128, verbose_name='real name')),
                ('registration_date', models.DateField(verbose_name='registration date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='username')),
                ('name', models.CharField(max_length=128, verbose_name='real name')),
                ('registration_date', models.DateField(verbose_name='registration date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
