# Generated by Django 3.2.7 on 2022-02-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20220214_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateField(auto_now_add=True, verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='registration_date',
            field=models.DateField(auto_now_add=True, verbose_name='registration date'),
        ),
    ]
